# Generated by Django 3.1.2 on 2020-11-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201110_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Servicios',
        ),
    ]
